POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTJhM2IyZDM4N2MzNzYyOTRiMDhhYyIsImlhdCI6MTYzODA0ODY5MCwiZXhwIjoxNjM4NjUzNDkwfQ.RFyzZmQAcyBTuNEqJL6Q1T2wzq7OFjiFs5uUhUuMhrc

{
    "dni": "420", 
	"phoneNumber": "420", 
	"password": "1",
	"firstName": "chillguire",
	"lastName": "chillguire",
	"status": "Active",
	"sex": "Other"
}
