DELETE http://localhost:3000/api/users/61a3ad1d80422fe639699349
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTNhY2IxODA0MjJmZTYzOTY5OTM0MiIsImlhdCI6MTYzODExNzM5NSwiZXhwIjoxNjM4NzIyMTk1fQ.PLAAKdf7YQE_t0m_SU1AyrqSovK1BpTRakPEnsRBFUo