DELETE https://arcane-reaches-20829.herokuapp.com/api/users/61a3ee2ca5d41247c9d4bd97
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTNlZDUzYTVkNDEyNDdjOWQ0YmQ4YiIsImlhdCI6MTYzODEzMzE2MiwiZXhwIjoxNjM4NzM3OTYyfQ.g26jSa-jUsHbIifqR-Tfw9Bksth5Z0oNKSVMzKvFg_E