POST http://localhost:3000/api/register
Content-Type: application/json

{
    "dni": "12345678B", 
	"phoneNumber": "1234", 
	"password": "123456",
	"firstName": "John",
	"lastName": "Doe",
	"sex": "Male"
}
