POST http://localhost:3000/api/register
Content-Type: application/json

{
    "dni": "12345678A", 
	"phoneNumber": "34123456789", 
	"password": "1",
	"firstName": "John",
	"lastName": "Doe",
	"sex": "Male"
}
